"""Mode C - the consult surface.

Six typed query kinds, one envelope. Read-only but for `record_application`,
which is the single permitted write and is gated by `policy.check_consult_write`.

Three properties are load-bearing and are the reason this module is shaped the
way it is:

**Constraints eliminate.** A GPU-only tool is not a lower-ranked answer for a
laptop; it is not an answer. Filters run before ranking and the count of what
they removed is returned, so a thin result set is explained rather than
mysterious.

**Every result says why.** `why` is assembled from which filters passed and
which terms matched - never generated by a model. A result that cannot explain
itself cannot be trusted or tuned.

**No model stands between the query and the index.** Structured filters,
FTS5 and vectors over verified notes cannot fabricate a resource, because they
can only return things that exist. A model may summarise afterwards.
"""
from __future__ import annotations

import json
import math
import re
import sqlite3
import time
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any, Iterable, Sequence

from . import embed as embed_mod
from . import index as index_mod
from . import policy
from .config import (CatalogueConfig, LICENSE_CLASSES, index_db_path, is_hub,
                     permitted_uses, vault_root)

INTENTS = ("orient", "donor", "pattern", "technique", "data", "precedent")

# Filterable axes. Closed on purpose: an unknown filter name is a validation
# error, not a silently ignored constraint that returns confident nonsense.
FILTER_FIELDS = (
    "license_class", "deployment_target", "hardware_footprint", "ecosystem",
    "domain_primary", "maturity_stage", "interface_protocol", "data_locality",
    "security_compliance",
 "agent_surface",)

STOPWORDS = frozenset("""
a an and are as at be but by can could do does for from get give has have how i
if in into is it its me my need not of on or should so than that the their then
there these they this to use used using want was what when where which who why
will with without would you your
""".split())

TOKEN = re.compile(r'"[^"]+"|[A-Za-z0-9_.+#-]{2,}')

DATASET_DOMAINS = {"Data", "Geospatial", "Civic_Tech", "Scientific_Computation"}
DATASET_TYPES = {"data_platform", "data_api_resource", "geospatial_resource",
                 "geospatial_library", "civic_tech_resource"}


# --------------------------------------------------------------- the envelope

@dataclass(frozen=True)
class Result:
    """Contract per spec 9.2."""

    kind: str            # resource | topic | pattern | application | dataset
                         # | access_point | criterion | aggregator | note
    name: str
    why: str             # REQUIRED - assembled, never generated
    score: float         # 0..1, comparable only within one response
    fields: dict = field(default_factory=dict)


@dataclass(frozen=True)
class Response:
    """Contract per spec 9.2."""

    intent: str
    results: tuple[Result, ...] = ()
    # The drop-downs and the size of the set they describe. Empty for intents
    # that do not filter; `matched` is the whole candidate set, `results` the
    # page of it that came back.
    facets: dict = field(default_factory=dict)
    # Three different quantities, and a cold agent reasonably tried to add two
    # of them together. `considered` is every resource the filters were applied
    # to; `filtered_out` is how many of those a constraint removed; `matched`
    # is how many survivors also matched the query. `matched + filtered_out`
    # does not equal `considered`, because most survivors match no term at all.
    considered: int = 0
    matched: int = 0
    # Addresses *inside* the sources above - a different grain, kept in its own
    # field so `limit` means one thing and a caller never has to notice a
    # change of `kind` mid-list.
    components: tuple[Result, ...] = ()
    # Things a ranked list cannot say about itself: that a constraint removed a
    # better answer, or that nothing here really covers the question.
    advisories: tuple[str, ...] = ()
    filtered_out: int = 0
    tier_reached: int = 1        # 1 index | 2 metadata | 3 notes
    next_step: str = ""
    partial: bool = False
    notes: tuple[str, ...] = ()

    def grouped(self) -> dict[str, list[Result]]:
        """Results by kind - `orient()` returns topics, resources and
        aggregators, and this is how a caller separates them."""
        out: dict[str, list[Result]] = {}
        for result in self.results:
            out.setdefault(result.kind, []).append(result)
        return out

    def to_dict(self) -> dict[str, Any]:
        return {
            "intent": self.intent,
            "results": [
                {"kind": r.kind, "name": r.name, "why": r.why,
                 "score": round(r.score, 4), "fields": r.fields}
                for r in self.results
            ],
            "facets": self.facets,
            "considered": self.considered,
            "matched": self.matched,
            "components": [
                {"kind": c.kind, "name": c.name, "why": c.why,
                 "score": round(c.score, 4), "fields": c.fields}
                for c in self.components],
            "advisories": list(self.advisories),
            "filtered_out": self.filtered_out,
            "tier_reached": self.tier_reached,
            "next_step": self.next_step,
            "partial": self.partial,
            "notes": list(self.notes),
        }



def axis_vocabulary() -> dict[str, tuple[str, ...]]:
    """The permitted value of every filterable axis, from the content model.

    [[Note Content Model]] is the authority and already parses into
    `content_model.axis_values`; reading it here means the vocabulary a caller
    is offered and the vocabulary `integrity` enforces cannot drift apart.

    Degrades to empty when the model is absent, in which case values are not
    checked - the same posture the shape checks take.
    """
    try:
        from .content_model import load as load_model

        model = load_model()
        return {axis: tuple(sorted(values))
                for axis, values in (model.axis_values or {}).items()}
    except Exception:
        return {}


def _check_axis_values(axis: str, values: Sequence[str]) -> None:
    """Refuse a value outside the axis, and say what the axis permits.

    Before 2026-09-06 an unrecognised value simply matched nothing, so
    `license_class="permissive"` - the obvious English guess, wrong only in
    case - returned `matched: 0, filtered_out: 130` and a next step reading
    *every candidate failed a constraint*. That is a true sentence about a
    false premise: nothing failed the constraint, the constraint was not a
    constraint. A cold agent hit this within two calls.
    """
    permitted = axis_vocabulary().get(axis)
    if not permitted:
        return
    unknown = [v for v in values if v not in permitted]
    if unknown:
        raise ValueError(
            f"{axis}={unknown[0]!r} is not a value of that axis. Permitted: "
            f"{list(permitted)}. Values are case-sensitive.")

@dataclass(frozen=True)
class Constraints:
    """Hard filters. Every field eliminates; none of them re-ranks."""

    license_class: tuple[str, ...] = ()
    deployment_target: tuple[str, ...] = ()
    hardware_footprint: tuple[str, ...] = ()
    ecosystem: tuple[str, ...] = ()
    domain_primary: tuple[str, ...] = ()
    maturity_stage: tuple[str, ...] = ()
    interface_protocol: tuple[str, ...] = ()
    data_locality: tuple[str, ...] = ()
    security_compliance: tuple[str, ...] = ()
    agent_surface: tuple[str, ...] = ()
    max_age_days: int | None = None
    exclude_containers: bool = False

    @classmethod
    def of(cls, raw: dict[str, Any] | "Constraints" | None) -> "Constraints":
        if isinstance(raw, Constraints):
            return raw
        raw = dict(raw or {})
        kwargs: dict[str, Any] = {}
        unknown = set(raw) - set(cls.__dataclass_fields__)
        if unknown:
            raise ValueError(
                f"unknown constraint(s): {sorted(unknown)}. Filterable axes are "
                f"{list(FILTER_FIELDS)} plus max_age_days and exclude_containers.")
        for key, value in raw.items():
            if key in FILTER_FIELDS:
                if value in (None, "", []):
                    continue
                values = (value,) if isinstance(value, str) else tuple(value)
                _check_axis_values(key, values)
                kwargs[key] = values
            elif value not in (None, ""):
                kwargs[key] = value
        return cls(**kwargs)

    def active(self) -> dict[str, Any]:
        out: dict[str, Any] = {}
        for name in FILTER_FIELDS:
            values = getattr(self, name)
            if values:
                out[name] = list(values)
        if self.max_age_days:
            out["max_age_days"] = self.max_age_days
        if self.exclude_containers:
            out["exclude_containers"] = True
        return out

    def describe(self) -> str:
        parts = [f"{k}={'|'.join(v) if isinstance(v, list) else v}"
                 for k, v in self.active().items()]
        return ", ".join(parts)


# ------------------------------------------------------------------- plumbing

def _conn(db_path: Path | None = None) -> sqlite3.Connection:
    conn = index_mod.connect(db_path)
    index_mod.init(conn)
    return conn


def terms_from(text: str) -> list[str]:
    """Query text to search terms.

    Quoted phrases survive intact, because "change data capture" is one thing
    and three stopword-adjacent tokens are not.
    """
    out: list[str] = []
    for match in TOKEN.findall(text or ""):
        token = match.strip('"').strip()
        if not token:
            continue
        if token.lower() in STOPWORDS and " " not in token:
            continue
        if token.lower() not in [t.lower() for t in out]:
            out.append(token)
    return out



# Frontmatter fields whose values describe *what a note is about*, and are
# therefore worth matching a query against. The nine taxonomy axes are
# deliberately absent: they are filter fields, and their values are identifiers
# that collide with ordinary words. `interface_protocol: "REST"` matched the
# 'rest' in "the rest of the system is out of scope", putting an unrelated
# dataset above everything. A category is something you filter on, not
# something you free-text search.
MATCHABLE_FRONTMATTER = ("glossary_terms", "patterns", "aliases", "repo_key",
                         "canonical_word", "term_key", "pattern_key", "topic_key",
                         "primary_topic", "secondary_topics", "type", "project")


def _matched_frontmatter(raw: str | None, terms: Sequence[str]) -> list[str]:
    """Query terms appearing as a whole value in a content-bearing field."""
    try:
        data = json.loads(raw or "{}")
    except ValueError:                                        # pragma: no cover
        return []
    values: set[str] = set()
    for key in MATCHABLE_FRONTMATTER:
        value = data.get(key)
        if isinstance(value, str):
            values.add(value.lower())
        elif isinstance(value, (list, tuple)):
            values.update(str(v).lower() for v in value)
    return [t for t in terms if t.lower() in values]


def _matched_terms_bounded(text: str, terms: Sequence[str]) -> list[str]:
    """Like `_matched_terms`, but a term must be a whole token.

    Names are short, so a substring match inside an unrelated word is a large
    proportion of the evidence rather than noise: 'review' matched inside
    `asreview` put a systematic-screening tool at the top of a query about
    contribution workflows. Word boundaries here, substrings elsewhere - in a
    long body of prose a substring hit is usually the word you meant.
    """
    low = text.lower()
    return [t for t in terms
            if re.search(rf"(?<![a-z0-9]){re.escape(t.lower())}(?![a-z0-9])", low)]


def _fts_query(terms: Sequence[str]) -> str:
    quoted = ['"' + t.replace('"', '') + '"' for t in terms if t.strip()]
    return " OR ".join(quoted)


def _matched_terms(text: str, terms: Sequence[str]) -> list[str]:
    low = text.lower()
    return [t for t in terms if t.lower() in low]


@dataclass(frozen=True)
class Hit:
    note: str
    layer: str
    heading: str
    excerpt: str
    matched: tuple[str, ...]
    rank: int


def lexical(conn: sqlite3.Connection, terms: Sequence[str],
            layers: Sequence[str] | None = None, limit: int = 60) -> list[Hit]:
    """FTS5/BM25 over note prose.

    Lexical goes first because it answers what embeddings handle worst: rare,
    specific tokens - *does anything here read Parquet*.
    """
    query = _fts_query(terms)
    if not query:
        return []
    sql = ("SELECT c.id AS id, c.note AS note, c.layer AS layer, c.heading AS heading, "
           "c.text AS text, bm25(chunk_fts) AS rank "
           "FROM chunk_fts JOIN chunk c ON c.id = chunk_fts.rowid "
           "WHERE chunk_fts MATCH ?")
    params: list[Any] = [query]
    if layers:
        marks = ",".join("?" for _ in layers)
        sql += f" AND c.layer IN ({marks})"
        params.extend(layers)
    sql += " ORDER BY rank LIMIT ?"
    params.append(limit)
    try:
        rows = conn.execute(sql, params).fetchall()
    except sqlite3.OperationalError:
        return []
    hits: list[Hit] = []
    for position, row in enumerate(rows, start=1):
        text = row["text"]
        hits.append(Hit(note=row["note"], layer=row["layer"],
                        heading=row["heading"] or "",
                        excerpt=_excerpt(text, terms),
                        matched=tuple(_matched_terms(f"{row['heading']} {text}", terms)),
                        rank=position))
    return hits


# A name hit on one term out of ten is not evidence about the note; it is a
# coincidence of vocabulary. `run-llama - llama_index` matching 'run' in the
# query "run twelve dependent jobs nightly and recover from partial failure"
# outranked `apache - airflow`, which matched four terms in its own
# `What It Solves`. The name ranking is deliberately weighted above the text
# ranking, so a weak hit inside it beats a strong hit outside it.
#
# The rule below keeps the behaviour the docstring promises - a short,
# name-shaped query resolves by name - and refuses the coincidence case.
NAME_MIN_QUERY_COVERAGE = 0.5   # share of the query a single-term hit must reach
NAME_MIN_NAME_COVERAGE = 0.5    # or share of the note's own name it must cover
NAME_SHORT_QUERY = 2            # queries this short are name lookups by intent


def _name_coverage(name: str, term: str) -> float:
    """How much of the note's own name this term accounts for.

    Compared on letters and digits only, so punctuation and the `owner - repo`
    convention do not distort it. `plumbing` is most of `Topic - Plumbing`;
    `run` is a sixth of `run-llama - llama_index`.
    """
    flat = "".join(ch for ch in name.lower() if ch.isalnum())
    if not flat:
        return 0.0
    return len("".join(ch for ch in term.lower() if ch.isalnum())) / len(flat)


def _name_hit_qualifies(matched: Sequence[str], terms: Sequence[str],
                        name: str = "") -> bool:
    """A name match earns its weighted ranking slot, or it does not appear.

    Two or more distinct query terms in one name is evidence on any query
    length. A single term is evidence when it is most of what was asked for,
    **or** most of what the note is called - and those are different tests.
    `orient("plumbing scheduler queue")` should still reach `Topic - Plumbing`,
    whose whole name is the matched term, while the same one-in-three coverage
    from `run` inside `run-llama - llama_index` is a coincidence of vocabulary.
    """
    if not matched or not terms:
        return False
    if len(terms) <= NAME_SHORT_QUERY:
        return True
    if len(matched) >= 2:
        return True
    if (len(matched) / len(terms)) >= NAME_MIN_QUERY_COVERAGE:
        return True
    return any(_name_coverage(name, term) >= NAME_MIN_NAME_COVERAGE
               for term in matched)


def by_name(conn: sqlite3.Connection, terms: Sequence[str],
            layers: Sequence[str] | None = None, limit: int = 30) -> list[Hit]:
    """Name and alias matching.

    Tier 1 of the cost ladder: *what is where*, answered without touching
    prose. `orient("airflow")` should find the Airflow note by its name, not
    by whichever paragraph happens to say the word most often.

    Two things are load-bearing here and were not always true. Hits are
    ordered by how much of the query they actually matched, not by whatever
    order SQLite returned the rows in - the position becomes the RRF rank, so
    row order was silently deciding relevance. And a hit must qualify under
    `_name_hit_qualifies` before it occupies a slot at all.
    """
    if not terms:
        return []
    clauses, params = [], []
    for term in terms:
        clauses.append("(LOWER(n.name) LIKE ? OR LOWER(n.frontmatter) LIKE ?)")
        params.extend([f"%{term.lower()}%", f'%"{term.lower()}"%'])
    sql = (f"SELECT n.name, n.layer, n.body, n.frontmatter FROM note n "
           f"WHERE ({' OR '.join(clauses)})")
    if layers:
        marks = ",".join("?" for _ in layers)
        sql += f" AND n.layer IN ({marks})"
        params.extend(layers)
    sql += " LIMIT ?"
    params.append(limit)
    rows = conn.execute(sql, params).fetchall()

    # A prose query carries words no stoplist catches - "Our", "Some", "we",
    # "review". Matching those against a note *name* and calling it evidence is
    # how "our reference manual carries code samples that were correct when
    # written" came back ranked on 'Our', 'Some', 'we'. Selectivity is measured
    # from the index, so the judgement is about this corpus rather than about
    # English.
    selective = _selective_terms(conn, terms)

    candidates: list[dict] = []
    for row in rows:
        # Which field actually matched, and nothing invented when none did.
        # An earlier version fell back to "the first search term" here, which
        # produced explanations asserting matches that had not happened.
        in_name = [t for t in _matched_terms_bounded(row["name"], terms)
                   if t.lower() in selective]
        matched = tuple(in_name)
        heading = "name" if in_name else "frontmatter"
        if not matched:
            matched = tuple(t for t in _matched_frontmatter(row["frontmatter"], terms)
                            if t.lower() in selective)
        if not matched:
            continue
        if not _name_hit_qualifies(matched, terms,
                                   row["name"] if in_name else ""):
            continue
        candidates.append({"name": row["name"], "layer": row["layer"],
                           "body": row["body"], "matched": matched,
                           "heading": heading})

    # More matched terms first; a name match ahead of a frontmatter-only match
    # on the same count; then the shorter name, which is the more specific one
    # when both contain the same term. Deterministic, so a rebuild reproduces
    # the same ranking.
    candidates.sort(key=lambda c: (-len(c["matched"]),
                                   0 if c["heading"] == "name" else 1,
                                   len(c["name"]), c["name"]))

    return [Hit(note=c["name"], layer=c["layer"], heading=c["heading"],
                excerpt=_excerpt(c["body"], terms), matched=c["matched"],
                rank=position)
            for position, c in enumerate(candidates, start=1)]


def _excerpt(text: str, terms: Sequence[str], width: int = 220) -> str:
    flat = " ".join((text or "").split())
    low = flat.lower()
    for term in terms:
        position = low.find(term.lower())
        if position >= 0:
            start = max(0, position - width // 3)
            return ("..." if start else "") + flat[start:start + width].strip() + \
                   ("..." if start + width < len(flat) else "")
    return flat[:width]


def rrf(rankings: Sequence[Sequence[str]], k: int = 60,
        weights: Sequence[float] | None = None) -> dict[str, float]:
    """Reciprocal Rank Fusion.

    Chosen over score blending because it needs no calibration between a BM25
    score and a cosine similarity, and each contributor stays inspectable.
    """
    weights = list(weights or [1.0] * len(rankings))
    scores: dict[str, float] = {}
    for ranking, weight in zip(rankings, weights):
        for position, name in enumerate(ranking, start=1):
            scores[name] = scores.get(name, 0.0) + weight / (k + position)
    return scores


def _normalise(scores: dict[str, float]) -> dict[str, float]:
    if not scores:
        return {}
    top = max(scores.values()) or 1.0
    return {name: value / top for name, value in scores.items()}


# --------------------------------------------------------------- hard filters

def eligible(conn: sqlite3.Connection, constraints: Constraints,
             candidates: Iterable[str] | None = None) -> tuple[set[str], int, str]:
    """Apply the hard filters. Returns (surviving names, eliminated, description).

    A resource whose value for a filtered axis is unknown is eliminated too.
    That is deliberate: "we do not know whether this runs on a laptop" is not
    an answer to "what runs on a laptop".
    """
    sql = "SELECT name, pushed_at, is_container FROM resource_facet WHERE 1=1"
    params: list[Any] = []
    for name in FILTER_FIELDS:
        values = getattr(constraints, name)
        if not values:
            continue
        marks = ",".join("?" for _ in values)
        sql += f" AND {name} IN ({marks})"
        params.extend(values)
    if constraints.exclude_containers:
        sql += " AND is_container = 0"
    rows = conn.execute(sql, params).fetchall()

    survivors = {row["name"] for row in rows}
    if constraints.max_age_days:
        horizon = datetime.now(timezone.utc) - timedelta(days=constraints.max_age_days)
        fresh = set()
        for row in rows:
            pushed = _parse_iso(row["pushed_at"])
            if pushed and pushed >= horizon:
                fresh.add(row["name"])
        survivors = fresh

    total = conn.execute("SELECT COUNT(*) AS n FROM resource_facet").fetchone()["n"]
    if candidates is not None:
        pool = set(candidates)
        eliminated = len(pool - survivors)
        survivors &= pool
    else:
        eliminated = total - len(survivors)
    return survivors, eliminated, constraints.describe()


def _parse_iso(value: str | None) -> datetime | None:
    if not value:
        return None
    try:
        parsed = datetime.fromisoformat(str(value).replace("Z", "+00:00"))
    except ValueError:
        return None
    return parsed if parsed.tzinfo else parsed.replace(tzinfo=timezone.utc)


# ------------------------------------------------------------------ retrieval

# Sections that assert what a source *does*, as against sections that record
# what is true *about* it. The distinction decides whether a term match is
# evidence for the source or merely evidence that the word appears in its note.
CLAIM_SECTIONS = frozenset({
    "bottom line", "what it solves", "architecture & mechanics",
    "what is inside", "transferable capability", "integration & use cases",
    "taxonomy", "definition", "why it matters", "inclusion criteria",
    "canonical vocabulary", "why this topic exists", "mechanics",
    "typical use cases", "what was needed", "what was found and taken",
    "what it replaced", "what the catalogue should learn", "name",
})

# Everything else a note carries: provenance, limits, corrections, links.
CAVEAT_SECTIONS = frozenset({"reading notes", "evidence", "sense notes",
                             "observed contexts", "frontmatter"})


def is_claim_section(heading: str) -> bool:
    """True when a match here is evidence the source does the thing.

    Unknown headings count as claims. A new section is more likely to describe
    a source than to caveat it, and the failure this guards against is the
    specific one where a caveat is read as a claim.
    """
    return (heading or "name").strip().lower() not in CAVEAT_SECTIONS


SELECTIVITY_CEILING = 0.50      # a term in most of the corpus cannot discriminate


ANSWERABLE_LAYERS = ("resource", "review", "paper")


def _selective_terms(conn: sqlite3.Connection, terms: Sequence[str],
                     ceiling: float | None = None,
                     scope: str = "answerable") -> frozenset[str]:
    """Which query terms are discriminating enough to count as coverage.

    Measured, not assumed: a term is selective when fewer than
    `SELECTIVITY_CEILING` of notes contain it. This is document frequency doing
    the job a stopword list does badly - `over` and `work` pass any reasonable
    stoplist and still carry no information about which note is wanted.

    **Two things make this statistic easy to get wrong, and both were.**

    *The denominator.* Document frequency was measured over every note in the
    vault. Only `resource`, `review` and `paper` notes can ever be an answer,
    and the other 211 - glossary, patterns, topics, this system's own design
    documents - are short and dilute the count. Measured over the notes that
    can actually be returned, `read` is in 96% of them, `file` 93%, `files`
    86%, `test` 73%: useless discriminators that the wrong denominator scored
    at 0.53, 0.48, 0.38 and 0.39 and waved through. `scope="answerable"` is
    the default from 2026-09-04.

    *The corpus moves.* A fixed share is a moving target - the 2026-09-04
    cohort took the vault from 81 resources to 128 - and so is the vault's own
    documentation. An earlier note here claimed raising the ceiling from 0.34
    to 0.50 recovered a scenario outright. **It did, and then it did not.**
    Re-measured after five index notes were edited, 0.34 and 0.50 are
    indistinguishable on `useful@5`. The gain was real and it was not the
    ceiling; it was the corpus. That is why `librarian relevance` exists and
    why nothing here should be settled by editing a constant and re-running.

    0.50 is kept because *a term in more than half the answerable corpus
    cannot discriminate* is a threshold with a reason, and because the grid in
    `rank_configs.json` puts it at the top jointly with `coverage_order=bm25`.

    **What was tried and rejected**: weighting the surviving terms by inverse
    document frequency (`coverage_order="idf"`, still selectable). It loses at
    every ceiling. IDF is computed over the corpus, so it scores `scope` (df
    0.05) and `want` (0.08) far above `file` - and those are artefacts of how a
    query is phrased, not signal. Document frequency cannot separate "rare and
    meaningful" from "rare and incidental".

    `config-validation-surface` fails under every configuration in the grid and
    neither knob is its cause. Its description names a storage engine and a
    query layer as explicitly *out of scope*, and those terms drive the result;
    the ask and the context are not distinguished. That one is open.
    """
    if not terms:
        return frozenset()
    bar = SELECTIVITY_CEILING if ceiling is None else ceiling
    if scope == "all":
        total = conn.execute("SELECT COUNT(*) AS n FROM note").fetchone()["n"] or 1
        count = ("SELECT COUNT(DISTINCT note) AS n FROM chunk WHERE text LIKE ?", ())
    else:
        marks = ",".join("?" for _ in ANSWERABLE_LAYERS)
        total = conn.execute(
            f"SELECT COUNT(*) AS n FROM note WHERE layer IN ({marks})",
            ANSWERABLE_LAYERS).fetchone()["n"] or 1
        count = (f"SELECT COUNT(DISTINCT c.note) AS n FROM chunk c "
                 f"JOIN note nt ON nt.name = c.note "
                 f"WHERE c.text LIKE ? AND nt.layer IN ({marks})", ANSWERABLE_LAYERS)
    keep: set[str] = set()
    for term in terms:
        row = conn.execute(count[0], (f"%{term}%", *count[1])).fetchone()
        if (row["n"] or 0) / total < bar:
            keep.add(term.lower())
    return frozenset(keep)



def _coverage_key(conn: sqlite3.Connection, order: str,
                  selective: frozenset[str], query: str = ""):
    """The sort key for covered notes, chosen by `CatalogueConfig.coverage_order`.

    `terms` was the only behaviour until 2026-09-04 and remains the default:
    more matched terms ranks higher, ties broken by the text ranking's own
    position. `bm25` reverses that priority, letting the score FTS5 already
    computed decide and using the term count only to break ties - which is
    worth being able to test, because a count treats `service` and `malformed`
    as equally decisive and BM25 does not. `idf` is retained as a control.
    """
    if order == "segment":
        # Weight a matched term by the role it played in the request: full for
        # the ask, `CONTEXT_WEIGHT` for surrounding description, zero for a
        # clause that ruled it out. Deleting excluded terms outright was
        # measured first and was worse - it shrinks the evidence base until
        # single-term matches win. Weighting keeps the evidence and reorders it.
        from .queryunderstanding import segment

        seg = segment(query)
        return lambda h: (-sum(seg.weight_of(t) for t in h.matched), h.rank)
    if order == "bm25":
        return lambda h: (h.rank, -len(h.matched))
    if order == "idf":
        weights = _term_idf(conn, selective)
        return lambda h: (-sum(weights.get(t.lower(), 0.0) for t in h.matched), h.rank)
    return lambda h: (-len(h.matched), h.rank)


def _term_idf(conn: sqlite3.Connection,
              terms: Iterable[str]) -> dict[str, float]:
    """Inverse document frequency over the note index.

    Only `coverage_order="idf"` uses this, and that setting loses. It is kept
    because a rejected option nobody can re-run is a claim rather than a
    finding - see `_selective_terms` for what was measured and why it failed.
    """
    total = conn.execute("SELECT COUNT(*) AS n FROM note").fetchone()["n"] or 1
    out: dict[str, float] = {}
    for term in terms:
        row = conn.execute(
            "SELECT COUNT(DISTINCT note) AS n FROM chunk WHERE text LIKE ?",
            (f"%{term}%",)).fetchone()
        share = (row["n"] or 0) / total
        out[term.lower()] = math.log(1.0 / share) if share > 0 else 0.0
    return out

def selectivity_distribution(terms: Sequence[str] | None = None,
                             db_path: Path | None = None,
                             cfg: CatalogueConfig | None = None) -> dict[str, Any]:
    """The document-frequency spread the ceiling is a cut through.

    `THRESHOLD_CARRIES_ITS_DISTRIBUTION`. This one is the reason the invariant
    exists: 0.34 was right at 81 resources and wrong at 128, and the change was
    found by a scenario regression rather than by anyone checking.

    With no `terms`, samples the vocabulary of the corpus itself, which is the
    right basis - a query term only matters relative to how common it is here.
    """
    import sqlite3

    cfg = cfg or CatalogueConfig.load()
    conn = sqlite3.connect(str(db_path or index_db_path()))
    conn.row_factory = sqlite3.Row
    try:
        if terms is None:
            rows = conn.execute(
                "SELECT text FROM chunk WHERE layer IN "
                f"({','.join('?' for _ in ANSWERABLE_LAYERS)}) LIMIT 400",
                ANSWERABLE_LAYERS).fetchall()
            counter: dict[str, int] = {}
            for row in rows:
                for word in set(terms_from(row["text"] or "")):
                    counter[word.lower()] = counter.get(word.lower(), 0) + 1
            terms = [w for w, _ in sorted(counter.items(),
                                          key=lambda kv: -kv[1])[:120]]
        marks = ",".join("?" for _ in ANSWERABLE_LAYERS)
        total = conn.execute(
            f"SELECT COUNT(*) AS n FROM note WHERE layer IN ({marks})",
            ANSWERABLE_LAYERS).fetchone()["n"] or 1
        shares = []
        for term in terms:
            row = conn.execute(
                f"SELECT COUNT(DISTINCT c.note) AS n FROM chunk c "
                f"JOIN note nt ON nt.name = c.note "
                f"WHERE c.text LIKE ? AND nt.layer IN ({marks})",
                (f"%{term}%", *ANSWERABLE_LAYERS)).fetchone()
            shares.append(((row["n"] or 0) / total, term))
    finally:
        conn.close()
    shares.sort()
    if not shares:
        return {}
    ceiling = cfg.selectivity_ceiling
    return {
        "answerable_notes": total,
        "terms_sampled": len(shares),
        "ceiling": ceiling,
        "median_share": round(shares[len(shares) // 2][0], 3),
        "eliminated": sum(1 for share, _ in shares if share >= ceiling),
        "kept": sum(1 for share, _ in shares if share < ceiling),
        "closest_below": [t for s, t in shares if s < ceiling][-5:],
        "closest_above": [t for s, t in shares if s >= ceiling][:5],
    }


def _search(conn: sqlite3.Connection, query: str, cfg: CatalogueConfig,
            layers: Sequence[str] | None, pool: int = 60
            ) -> tuple[dict[str, float], dict[str, Hit], list[str], int]:
    """Filters -> lexical -> vectors -> RRF. Returns scores, best hit per note,
    degradation notes, and the deepest tier consulted."""
    terms = terms_from(query)
    if cfg.query_segmentation:
        # Terms a request names in order to rule them out are not the request.
        # See `queryunderstanding`; measured through `librarian relevance`
        # rather than assumed, because a segmenter fitted to one author's
        # phrasing produces a number and no capability.
        from .queryunderstanding import segment

        excluded = set(segment(query).excluded)
        if excluded:
            kept = [t for t in terms if t.lower() not in excluded]
            if kept:                     # never leave a query with nothing
                terms = kept
    name_hits = by_name(conn, terms, layers)
    text_hits = lexical(conn, terms, layers, limit=pool)

    best: dict[str, Hit] = {}
    for hit in name_hits + text_hits:
        current = best.get(hit.note)
        if current is None or hit.rank < current.rank:
            best[hit.note] = hit

    # A third contributor: how much of the query each note actually matched.
    #
    # RRF fuses *positions*, not strengths, so a note ranked first in the
    # lexical list on one common term outranks one ranked second on four. That
    # is how `neo4j-labs - neocarta` (matching 'database') came to beat
    # `osquery - osquery` (matching 'operating', 'system', 'database') for
    # "query the operating system state as if it were a database".
    #
    # Coverage needs no calibration - it is a count of distinct query terms
    # already computed for the `why` string - so it enters as another ranking
    # rather than as a score multiplier, which keeps every contributor
    # inspectable and keeps RRF doing the only job it is good at.
    # ...but only where the match is a *claim*. A note's sections do different
    # jobs: some assert what the source does, others record what is wrong with
    # it. `Reading Notes` on `shenhuan2021 - gudu-sql-omni-introduce` contains
    # 'SQL', 'transformations' and 'lineage' inside the sentence "It is not
    # that" - a caveat quoting the description it exists to refute. Counting
    # that as evidence the source does the thing put it above `dbt-core`.
    #
    # Caveats stay searchable, because "which sources are abandoned" is a real
    # question. They simply do not earn coverage credit.
    # Count only terms that actually discriminate. `over`, `work` and `no`
    # survive the stopword list but appear in most of the vault, so counting
    # them lets a note match four words of a query while sharing nothing
    # specific with it. Selectivity is measured from the index rather than
    # guessed: a term in more than a third of notes carries no information
    # about which note you want.
    selective = _selective_terms(conn, terms, cfg.selectivity_ceiling,
                                 cfg.selectivity_scope)

    # Narrow every hit to the terms that actually counted, before anything reads
    # them. `hit.matched` is what the `why` string reports, so leaving the
    # discarded terms on it would have the explanation claim evidence the
    # ranking refused to use - 'each' and 'one' presented as reasons.
    def only_counted(hits: list[Hit]) -> list[Hit]:
        return [Hit(h.note, h.layer, h.heading, h.excerpt,
                    tuple(t for t in h.matched if t.lower() in selective), h.rank)
                for h in hits]

    text_hits = only_counted(text_hits)
    name_hits = only_counted(name_hits)
    best = {}
    for hit in name_hits + text_hits:
        current = best.get(hit.note)
        if current is None or hit.rank < current.rank:
            best[hit.note] = hit

    by_note: dict[str, Hit] = {}
    for hit in text_hits + name_hits:
        if not is_claim_section(hit.heading):
            continue
        current = by_note.get(hit.note)
        if current is None or len(hit.matched) > len(current.matched):
            by_note[hit.note] = hit
    # How a covered note is ordered is a stage, not a constant. `terms` counts
    # matched terms equally; `bm25` defers to the score the text ranking
    # already trusts, which has term saturation and length normalisation that a
    # count does not; `idf` is the naive weighting that was measured and lost,
    # kept selectable so the rejection stays reproducible rather than folklore.
    covered = sorted(by_note.values(),
                     key=_coverage_key(conn, cfg.coverage_order, selective, query))
    coverage = [h.note for h in covered
                if len(h.matched) >= cfg.coverage_min_terms]

    # One entry per note, keeping its best-placed chunk.
    #
    # RRF is defined over rankings of distinct items. `lexical` returns a
    # *chunk* ranking, so a note appears once per matching section and `rrf`
    # sums each appearance - which quietly turns "how many of my sections
    # mention this" into a ranking signal. It rewards verbose notes, and it got
    # worse every time a section was added to the schema: it is why
    # `shenhuan2021 - gudu-sql-omni-introduce`, whose four sections all discuss
    # SQL lineage, outranked `dbt-labs - dbt-core`, which does it.
    def first_per_note(hits: list[Hit]) -> list[str]:
        seen: set[str] = set()
        out: list[str] = []
        for hit in hits:
            if hit.note not in seen:
                seen.add(hit.note)
                out.append(hit.note)
        return out

    rankings = [first_per_note(name_hits), first_per_note(text_hits), coverage]
    weights = [cfg.lexical_weight * cfg.name_weight_multiplier,
               cfg.lexical_weight,
               cfg.lexical_weight * cfg.coverage_weight_multiplier]
    degraded: list[str] = []
    tier = 1 if not text_hits else 3

    if cfg.embeddings_enabled:
        vector_hits, reason = embed_mod.search(conn, query, cfg, limit=pool, layers=layers)
        if reason:
            degraded.append(reason)
        else:
            ordered: list[str] = []
            for _, note_name, score in vector_hits:
                if note_name not in ordered:
                    ordered.append(note_name)
                    best.setdefault(note_name, Hit(
                        note=note_name, layer="", heading="",
                        excerpt="", matched=(), rank=len(ordered)))
            rankings.append(ordered)
            weights.append(cfg.vector_weight)
            if ordered:
                tier = 3

    return _normalise(rrf(rankings, cfg.rrf_k, weights)), best, degraded, tier


def _facets(conn: sqlite3.Connection, names: Iterable[str]) -> dict[str, dict]:
    names = list(names)
    if not names:
        return {}
    marks = ",".join("?" for _ in names)
    rows = conn.execute(
        f"SELECT * FROM resource_facet WHERE name IN ({marks})", names).fetchall()
    return {row["name"]: dict(row) for row in rows}



# --------------------------------------------------------------------- facets

# Which axes a person may narrow on, in the order a page should show them.
# `license_class` leads because it is the one that eliminates most sharply and
# the one a reader most often has a fixed answer to.
FACET_FIELDS = ("license_class", "domain_primary", "ecosystem", "maturity_stage",
                "deployment_target", "interface_protocol", "hardware_footprint",
                "data_locality", "agent_surface", "security_compliance")


def facet_counts(conn: sqlite3.Connection,
                 names: Iterable[str]) -> dict[str, list[dict]]:
    """Per-axis value counts over a candidate set. The drop-downs, as data.

    Computed from **the results**, never from the vocabulary. Searching
    *parser* should offer `ecosystem: Mixed (4), Web_Frontend (3)` and not the
    full fourteen-value enumeration with eleven zeroes - a facet listing values
    that cannot be selected is a menu of dead ends.

    Two properties fall out of decisions already made elsewhere, and both are
    the reason this belongs in the engine rather than in a page:

    - **A count is the size of the surviving set.** `eligible` removes
      candidates rather than demoting them, so choosing a value leaves exactly
      that many. The reader sees the cost of a constraint before paying it,
      which is the honest form of a filter.
    - **An axis that does not vary is omitted.** One value across every
      candidate narrows nothing, and saying so is a statement about coverage
      the ranked list cannot make.

    Returned to the MCP surface and the web app alike, so neither reimplements
    it and they cannot disagree.
    """
    rows = _facets(conn, names)
    if not rows:
        return {}
    out: dict[str, list[dict]] = {}
    for field in FACET_FIELDS:
        counts: dict[str, int] = {}
        for facet in rows.values():
            value = facet.get(field)
            if value in (None, ""):
                continue
            counts[str(value)] = counts.get(str(value), 0) + 1
        if len(counts) < 2:
            continue                    # an axis with one value narrows nothing
        out[field] = [{"value": value, "count": count}
                      for value, count in sorted(counts.items(),
                                                 key=lambda kv: (-kv[1], kv[0]))]
    return out


# ------------------------------------------------------- component retrieval

COMPONENT_LIMIT = 3

# A directory name in more than this share of surveyed sources says nothing
# about which source you want. `test`, `src` and `docs` are in almost all of
# them. Same reasoning as `SELECTIVITY_CEILING`, one grain down, and it ships
# with `component_name_distribution()` per `THRESHOLD_CARRIES_ITS_DISTRIBUTION`.
COMPONENT_SELECTIVITY_CEILING = 0.25


def find_components(terms: Sequence[str], limit: int = COMPONENT_LIMIT,
                    db_path: Path | None = None,
                    allowed_notes: Iterable[str] | None = None,
                    inherited: dict[str, dict[str, Any]] | None = None) -> list[Result]:
    """Addresses inside a source, not just the source.

    Every query until 2026-09-05 returned `kind: resource` - a whole repository -
    while the data layer held 2,761 directories and 4,877 component paths that
    no query could reach. The notes make the case against that themselves:
    `What Is Inside` exists because a source's most valuable content is
    routinely not what its abstract describes, and `elastic-labs` is catalogued
    for search while the thing worth opening is `example-apps/relevance-workbench`.

    So this returns the address. It reads the component store, never the vault,
    and it invents nothing: a component result exists only because a survey
    recorded that path at a known commit, which makes every one of them
    traceable in the sense [[Data Information Knowledge]] requires.

    **Capped deliberately.** Fine-grained results outnumber coarse ones by two
    orders of magnitude, so without a cap they would flood every answer. Three
    is enough to say *and look here specifically* and too few to bury the notes.

    **`allowed_notes` is not optional in practice.** The first version appended
    components *after* filtering, so a query constrained to `Permissive` came
    back with addresses inside sources the constraint had just eliminated. Nine
    existing tests failed at once and they were right to: *constraints
    eliminate* is the invariant this system is built on, and a component is
    part of the source it belongs to, not an exception to it.
    """
    from .components import connect
    from .config import component_db_path

    target = Path(db_path or component_db_path())
    if not target.exists() or not terms:
        return []
    wanted = [t.lower() for t in terms if len(t) > 3]
    if not wanted:
        return []

    conn = connect(target)
    try:
        scored: dict[tuple[str, str], dict[str, Any]] = {}

        def add(repo_key: str, address: str, kind: str, term: str,
                detail: str) -> None:
            key = (repo_key, address)
            row = scored.setdefault(key, {"repo_key": repo_key, "address": address,
                                          "kind": kind, "terms": set(),
                                          "detail": detail})
            row["terms"].add(term)

        total = conn.execute("SELECT COUNT(*) FROM source").fetchone()[0] or 1

        def selective(term: str) -> bool:
            """Does this term pick out a source, or is it in most of them?

            `test` is a directory in nearly every surveyed repository, so
            matching it names no source in particular. Measured, not listed -
            a stoplist here would need maintaining and would still miss the
            next ubiquitous name.
            """
            row = conn.execute(
                "SELECT COUNT(DISTINCT repo_key) n FROM directory "
                "WHERE lower(name) = ?", (term,)).fetchone()
            return (row["n"] or 0) / total < COMPONENT_SELECTIVITY_CEILING

        for term in wanted:
            if not selective(term):
                continue
            like = f"%{term}%"
            for row in conn.execute(
                    "SELECT repo_key, parent, name, files FROM directory "
                    "WHERE name LIKE ? ORDER BY files DESC LIMIT 24", (like,)):
                # Whole-segment matching. `LIKE '%side%'` returns `sidekiq` and
                # `SideNav`, which is the substring defect this system already
                # fixed once for `interface_protocol: "REST"` matching *the rest
                # of the system* - and which `F:\Mark-XLVIII-main` documents
                # fixing independently in its own capability search.
                if not _matched_terms_bounded(row["name"], [term]):
                    continue
                address = (f"{row['parent']}/{row['name']}" if row["parent"]
                           else row["name"])
                add(row["repo_key"], address, "directory", term,
                    f"{row['files']} files")
            for table, detail in (("path", ""), ("signal_path", "sampled")):
                column = "path"
                for row in conn.execute(
                        f"SELECT repo_key, {column} FROM {table} "
                        f"WHERE {column} LIKE ? LIMIT 24", (like,)):
                    segments = row[column].replace("/", " ").replace(".", " ")
                    if not _matched_terms_bounded(segments, [term]):
                        continue
                    add(row["repo_key"], row[column], "file", term, detail)

        notes = {r["repo_key"]: r["note"] for r in
                 conn.execute("SELECT repo_key, note FROM source")}
    except sqlite3.OperationalError:
        # No component store, or one built by an older schema. Same posture as
        # LM Studio, graphify and the toolchain: return nothing and let the
        # caller carry on, never raise into a query.
        return []
    finally:
        conn.close()

    inherited = inherited or {}
    if allowed_notes is not None:
        permitted = set(allowed_notes)
        scored = {key: row for key, row in scored.items()
                  if notes.get(row["repo_key"]) in permitted}

    ranked = sorted(scored.values(), key=lambda r: (-len(r["terms"]),
                                                    len(r["address"])))
    out: list[Result] = []
    for row in ranked[:limit]:
        matched = sorted(row["terms"])
        why = ("matched " + ", ".join(f"'{m}'" for m in matched[:3])
               + f" in a {row['kind']} recorded by the survey of "
                 f"{row['repo_key']}")
        if row["detail"]:
            why += f" ({row['detail']})"
        note_name = notes.get(row["repo_key"]) or ""
        fields = {"repo_key": row["repo_key"], "address": row["address"],
                  "component_kind": row["kind"], "matched": matched,
                  "note": note_name}
        # Inherit the source's taxonomy. A component *is* filtered - it is only
        # offered when its note survived - but without these fields it looks
        # unfiltered, and a cold agent reading `license_class: None` on a row
        # returned under `license_class=Permissive` reasonably concluded the
        # constraint had been bypassed. A constraint you cannot verify held is
        # one a caller must assume did not.
        fields.update(inherited.get(note_name) or {})
        out.append(Result(
            "component", f"{row['repo_key']} > {row['address']}", why, 0.55,
            fields))
    return out


def component_name_distribution(db_path: Path | None = None) -> dict[str, Any]:
    """How common directory names are, so the ceiling is derived not guessed.

    `THRESHOLD_CARRIES_ITS_DISTRIBUTION`. Run after a large intake; a share
    fixed against a corpus that has doubled is not a threshold.
    """
    from .components import connect
    from .config import component_db_path

    target = Path(db_path or component_db_path())
    if not target.exists():
        return {}
    conn = connect(target)
    try:
        total = conn.execute("SELECT COUNT(*) FROM source").fetchone()[0] or 1
        rows = conn.execute(
            "SELECT lower(name) name, COUNT(DISTINCT repo_key) n FROM directory "
            "GROUP BY 1 ORDER BY 2 DESC LIMIT 15").fetchall()
        return {"sources": total, "ceiling": COMPONENT_SELECTIVITY_CEILING,
                "most_common": [(r["name"], round(r["n"] / total, 3)) for r in rows]}
    finally:
        conn.close()

def _why(hit: Hit | None, filters: str, extra: str = "") -> str:
    """Assembled from evidence, never written by a model."""
    parts: list[str] = []
    if hit and hit.matched:
        if hit.heading == "name":
            where = " in the note name"
        elif hit.heading == "frontmatter":
            where = " in the frontmatter"
        elif hit.heading:
            where = f" in ## {hit.heading}"
        else:
            where = ""
        parts.append("matched " + ", ".join(f"'{t}'" for t in hit.matched[:4]) + where)
    else:
        # Reached by vector similarity alone. Saying so is the honest
        # explanation; naming a term that did not match would not be.
        parts.append("closest by meaning; no exact term matched")
    if extra:
        parts.append(extra)
    if filters:
        parts.append(f"passed filters: {filters}")
    return "; ".join(parts) or "matched the query"


def _proven_use_bonus(facet: dict | None) -> tuple[float, str]:
    """A resource with a recorded successful use outranks a plausible stranger.

    Log-dampened for the same reason star counts are: one loud record must not
    bury a better-fitting resource nobody has written up yet.
    """
    count = int((facet or {}).get("application_count") or 0)
    if count <= 0:
        return 0.0, ""
    import math
    return min(0.15, 0.08 * math.log1p(count)), f"used in {count} application record(s)"


# ---------------------------------------------------------------- the six + 2


def _communities_touching(conn: sqlite3.Connection, names: set[str],
                          limit: int = 2) -> list[Result]:
    """Community reports whose members include something already matched.

    Only the ones that *cross topics* are offered. A community confined to one
    topic mostly restates that topic, and the topic index is the better answer
    for it; a community spanning several is the finding, because nobody
    assigned it.
    """
    if not names:
        return []
    try:
        rows = conn.execute(
            "SELECT community, label, size, topics, summary, members "
            "FROM community_report ORDER BY size DESC").fetchall()
    except sqlite3.OperationalError:          # index predates the table
        return []
    out: list[Result] = []
    for row in rows:
        try:
            members = set(json.loads(row["members"] or "[]"))
            topics = json.loads(row["topics"] or "{}")
        except ValueError:                    # pragma: no cover
            continue
        overlap = members & names
        if not overlap or len([t for t in topics if t]) < 2:
            continue
        out.append(Result(
            "community", f"Community {row['community']}",
            f"a grouping the vault graph found, containing {', '.join(sorted(overlap)[:2])}; "
            f"spans {len(topics)} topics",
            0.30,
            {"size": row["size"], "topics": topics, "summary": row["summary"],
             "members": sorted(members)}))
        if len(out) >= limit:
            break
    return out


def orient(topic_or_keywords: str, limit: int = 10, *, db_path: Path | None = None,
           cfg: CatalogueConfig | None = None) -> Response:
    """R1 - what is here, and where does this subject live?"""
    cfg = cfg or CatalogueConfig.load()
    conn = _conn(db_path)
    try:
        scores, best, degraded, _ = _search(conn, topic_or_keywords, cfg,
                                            layers=None, pool=80)
        results: list[Result] = []

        topics = _top(scores, best, ("topic",), conn, limit=min(limit, 5))
        for name, score, hit in topics:
            results.append(Result("topic", name, _why(hit, ""), score,
                                  _topic_fields(conn, name)))

        # Resources under a matched topic come first: the topic answered the
        # question, so its members are the answer's contents rather than a
        # separate lexical guess.
        under: list[str] = []
        for name, _, _ in topics:
            under.extend(_children_of(conn, name))
        facets = _facets(conn, set(under) | set(scores))

        resources = _top(scores, best, ("resource", "review", "paper"), conn, limit=limit)
        seen = {name for name, _, _ in resources}
        for name in under:
            if name not in seen and len(resources) < limit:
                resources.append((name, 0.35, None))
                seen.add(name)

        for name, score, hit in resources:
            facet = facets.get(name, {})
            kind = "aggregator" if facet.get("is_container") else "resource"
            extra = ""
            if hit is None:
                parent = _parent_topic(conn, name)
                extra = f"listed under {parent}" if parent else "in the matched topic"
            results.append(Result(kind, name, _why(hit, "", extra), score,
                                  _resource_fields(facet)))

        # A community the graph found, containing something already matched.
        # `orient` is the "what is this area" query, so a grouping nobody
        # assigned belongs in its answer - and a report is the only artefact
        # that can say what the catalogue has *become* rather than what somebody
        # filed. Read from the index, never computed here (spec 4B R6), and
        # advisory: it names a shape, it does not reassign anything (R3).
        matched = {r.name for r in results}
        for community in _communities_touching(conn, matched):
            results.append(community)

        aggregators = [r for r in results if r.kind == "aggregator"]
        return Response(
            intent="orient",
            results=tuple(results),
            tier_reached=3 if any(h for _, _, h in resources) else 2,
            next_step=(f"open the topic index for a full listing, or call find_donor "
                       f"with your constraints to narrow {len(results)} candidates"
                       if results else
                       "nothing matched; try broader keywords, or check the domain "
                       "register for whether this subject is in scope yet"),
            partial=bool(degraded),
            notes=tuple(degraded) + ((f"{len(aggregators)} of these are aggregators - "
                                      "lists of resources rather than resources",)
                                     if aggregators else ()),
        )
    finally:
        conn.close()


def find_donor(need: str, constraints: dict | Constraints | None = None,
               limit: int = 10, *, db_path: Path | None = None,
               cfg: CatalogueConfig | None = None) -> Response:
    """R2 - what could I take, given what I can actually run?"""
    cfg = cfg or CatalogueConfig.load()
    bounds = Constraints.of(constraints)
    conn = _conn(db_path)
    try:
        scores, best, degraded, tier = _search(conn, need, cfg,
                                               layers=("resource", "review", "paper"),
                                               pool=80)
        survivors, eliminated, described = eligible(conn, bounds)
        total_pool = len(survivors) + eliminated
        # Filters eliminate before ranking. A candidate that fails a
        # constraint is absent, not demoted.
        kept = {name: score for name, score in scores.items() if name in survivors}

        # Which of the *best* candidates the constraints removed. Silently
        # dropping the top hit and returning the next thing is how a caller ends
        # up reusing a Markdown parser for SQL: the honest answer to "parse SQL,
        # permissive only" may be that the only SQL parser here is copyleft, and
        # the response has to be able to say so.
        removed_best = [name for name, _ in
                        sorted(scores.items(), key=lambda kv: -kv[1])[:3]
                        if name not in survivors]

        # Structured filters are usable with no search machinery at all
        # (spec 3.2, stage 1). When nothing matched lexically but the
        # constraints are real, list what survives rather than nothing:
        # "everything permissive that runs on a server" is a valid question.
        filters_only = not kept and survivors and bounds.active()
        if filters_only:
            kept = {name: 0.5 for name in survivors}
        facets = _facets(conn, kept)

        ordered = sorted(kept.items(),
                         key=lambda kv: (-kv[1], -(facets.get(kv[0], {}).get("stars") or 0))
                         if filters_only else -kv[1])
        ranked: list[Result] = []
        for name, score in ordered[:limit]:
            facet = facets.get(name, {})
            bonus, bonus_why = _proven_use_bonus(facet)
            extra = bonus_why
            if filters_only:
                extra = "; ".join(x for x in (
                    "no term matched; listed because it survives the constraints",
                    bonus_why) if x)
            hit = best.get(name)
            fields = _resource_fields(facet)
            # The terms that actually matched, structurally rather than inside
            # the `why` sentence. `coverage.assess` needs them, and a caller
            # deciding whether to trust an answer should not have to parse prose.
            fields["matched"] = list(hit.matched) if hit else []
            fields["matched_in"] = hit.heading if hit else ""
            ranked.append(Result(
                "resource", name, _why(hit, described, extra),
                min(1.0, score + bonus), fields))
        ranked.sort(key=lambda r: -r.score)

        # Over `kept`, not over `ranked`: a shop counts every match and shows
        # you the first page. Facets computed from five results would narrow
        # nothing and would misreport what choosing a value costs.
        available = facet_counts(conn, kept)

        # A different grain, returned in a different field. Mixing them into
        # `results` made `limit` ambiguous - `limit=3` returned four rows - and
        # left a caller to notice the change of kind for themselves. `limit`
        # now means *sources*, because that is what somebody asking for five
        # candidates means, and components are supplementary detail about those
        # sources rather than competitors to them.
        #
        # Restricted to sources that survived the filters: a component of an
        # eliminated source is still eliminated.
        components: tuple[Result, ...] = ()
        if cfg.include_components and kept:
            components = tuple(find_components(
                terms_from(need), allowed_notes=set(kept),
                inherited={n: _resource_fields(facets.get(n, {}))
                           for n in kept}))

        # Two things the caller cannot see from a ranked list, and which decide
        # whether it should act on one: did a constraint remove a better answer,
        # and is this response worth trusting at all.
        advisories: list[str] = []
        if removed_best and bounds.active():
            advisories.append(
                f"{len(removed_best)} of the highest-scoring candidates were "
                f"removed by your constraints ({described}): "
                f"{', '.join(removed_best)}. If none of the results below fits, "
                f"the honest answer may be that the catalogue holds no match "
                f"under those constraints rather than the one it returned.")

        from .coverage import assess as _assess
        verdict = _assess(need, Response(intent="donor", results=tuple(ranked)),
                          db_path=db_path, cfg=cfg)
        if verdict.level != "covered":
            advisories.append(verdict.sentence())

        if ranked and verdict.level == "uncovered":
            next_step = ("nothing here covers this. Treat the results below as "
                         "the nearest material rather than as answers, and "
                         "record the gap.")
        elif ranked:
            next_step = (f"read the Bottom Line of the top {min(3, len(ranked))}, then "
                         f"open a workbench on the one you choose - the catalogue "
                         f"locates donors, it does not extract them")
        elif eliminated:
            next_step = (f"every candidate failed a constraint ({described}); relax one "
                         f"or record the gap - {eliminated} were eliminated")
        else:
            next_step = "nothing matched; try the vocabulary the domain itself uses"

        return Response(intent="donor", results=tuple(ranked),
                        components=components,
                        facets=available, matched=len(kept),
                        considered=total_pool,
                        filtered_out=eliminated, advisories=tuple(advisories),
                        tier_reached=2 if (filters_only or not ranked) else tier,
                        next_step=next_step,
                        partial=bool(degraded), notes=tuple(degraded))
    finally:
        conn.close()


def find_pattern(problem: str, limit: int = 5, *, db_path: Path | None = None,
                 cfg: CatalogueConfig | None = None) -> Response:
    """R3 - has this shape of problem been solved before, and by what?"""
    cfg = cfg or CatalogueConfig.load()
    conn = _conn(db_path)
    try:
        scores, best, degraded, tier = _search(conn, problem, cfg,
                                               layers=("pattern",), pool=40)
        patterns = _top(scores, best, ("pattern",), conn, limit=limit)
        results: list[Result] = []
        for name, score, hit in patterns:
            results.append(Result("pattern", name, _why(hit, ""), score,
                                  _pattern_fields(conn, name)))

        # Examples and neighbours come from the link graph, which is already
        # in the notes - no separate traversal store is needed for this.
        if patterns:
            head = patterns[0][0]
            for example in _incoming(conn, head, "implements_pattern"):
                results.append(Result(
                    "resource", example,
                    f"implements_pattern -> {head}", 0.6,
                    _resource_fields(_facets(conn, [example]).get(example, {}))))
            for related in _related_patterns(conn, head):
                results.append(Result("pattern", related,
                                      f"shares a topic or link with {head}", 0.4,
                                      _pattern_fields(conn, related)))

        return Response(
            intent="pattern", results=tuple(results), tier_reached=tier if results else 1,
            next_step=("read the pattern, then compare the example implementations - "
                       "they solve the same shape differently"
                       if results else
                       "no pattern matched; if the shape recurs, it is worth writing one"),
            partial=bool(degraded), notes=tuple(degraded))
    finally:
        conn.close()


def find_technique(what: str, source: str | None = None, limit: int = 10, *,
                   db_path: Path | None = None,
                   cfg: CatalogueConfig | None = None) -> Response:
    """R4 - where would I look to see how this is done?

    A locator, not an extractor. This query ends at tier 3 and says so: the
    technique itself lives in the source, and reaching it means opening a
    workbench, which is a person's decision. Nothing here fetches, clones or
    slices - the read path stays fast and side-effect free, which is what
    makes it safe to expose to third-party agents.
    """
    cfg = cfg or CatalogueConfig.load()
    conn = _conn(db_path)
    try:
        layers = ("resource", "review", "paper", "application", "pattern")
        scores, best, degraded, tier = _search(conn, what, cfg, layers=layers, pool=80)

        note_for_source = None
        if source:
            note_for_source = _note_for_source(conn, source)
            if note_for_source is None:
                return Response(
                    intent="technique", results=(), tier_reached=1,
                    next_step=(f"'{source}' is not catalogued. Add it through the intake "
                               f"(`python -m scout` directed mode) before asking where "
                               f"inside it to look."),
                    notes=("refused: the consult surface never fetches a source; "
                           "cataloguing is an intake operation subject to intake gates",))
            scores = {k: v for k, v in scores.items() if k == note_for_source}
            if note_for_source not in scores:
                scores[note_for_source] = 0.5

        facets = _facets(conn, scores)
        sources: list[Result] = []
        evidence: list[Result] = []
        for name, score in sorted(scores.items(), key=lambda kv: -kv[1]):
            hit = best.get(name)
            facet = facets.get(name)
            fields = _resource_fields(facet)
            if hit:
                fields["evidence"] = hit.excerpt
                fields["evidence_section"] = hit.heading
            if facet:
                if len(sources) < limit:
                    sources.append(Result(
                        "resource", name,
                        _why(hit, "", "described as relevant to the technique"),
                        score, fields))
            elif not is_hub(_note_type(conn, name)) and len(evidence) < 3:
                # A pattern or an application record does not contain the
                # technique, but it says who does - so it is returned as
                # supporting evidence, not as somewhere to go and look.
                evidence.append(Result(
                    "note", name, _why(hit, "", "context that points at a source"),
                    score * 0.5, fields))

        results = sources + evidence
        head = sources[0] if sources else None
        repo = (head.fields.get("repo_key") or head.name) if head else ""
        return Response(
            intent="technique", results=tuple(results), tier_reached=3 if results else 1,
            next_step=(f"open a workbench on {repo} to confirm - the catalogue records "
                       f"where a technique is likely to live, not the technique itself"
                       if head else
                       "nothing described this technique; the catalogue cannot say where "
                       "to look, which is a gap worth recording"),
            partial=bool(degraded),
            notes=tuple(degraded) + (
                "slices are ephemeral by design: no permanent index of extracted "
                "symbols exists, so this answer ends at the source, not inside it",))
    finally:
        conn.close()


def find_data(subject: str, purpose: str | None = None, limit: int = 10, *,
              db_path: Path | None = None,
              cfg: CatalogueConfig | None = None) -> Response:
    """R5 - what data exists for this, and how do I reach it?

    Returns datasets, the access points that address them, and any validation
    criteria a real application record has already established. The third of
    those is the need [[Application - Quantum Simulation Project]] identified:
    a maturing project needs data and validation points, not more method.
    """
    cfg = cfg or CatalogueConfig.load()
    query = f"{subject} {purpose or ''}".strip()
    conn = _conn(db_path)
    try:
        scores, best, degraded, tier = _search(
            conn, query, cfg, layers=("resource", "review", "paper", "application"),
            pool=80)
        facets = _facets(conn, scores)

        results: list[Result] = []
        eliminated = 0
        with_addresses = _sources_with_access_points(conn)
        for name, score in sorted(scores.items(), key=lambda kv: -kv[1]):
            facet = facets.get(name)
            if facet is None:
                continue
            # A recorded address is the strongest evidence that a source
            # serves data, and it outranks any taxonomy guess about it.
            data_shaped = (facet.get("domain_primary") in DATASET_DOMAINS
                           or _note_type(conn, name) in DATASET_TYPES
                           or facet.get("interface_protocol") in {"REST", "GraphQL"}
                           or name in with_addresses
                           or (facet.get("repo_key") or "") in with_addresses)
            if not data_shaped:
                eliminated += 1
                continue
            if len(results) >= limit:
                continue
            results.append(Result(
                "dataset", name,
                _why(best.get(name), "",
                     f"data-shaped: domain {facet.get('domain_primary')}, "
                     f"protocol {facet.get('interface_protocol')}"),
                score, _resource_fields(facet)))

        dataset_names = [r.name for r in results]
        for row in _access_points_for(conn, dataset_names):
            results.append(Result(
                "access_point", row["id"],
                f"address recorded for {row['source']}"
                + (f", verified {row['verified_at']}" if row["verified_at"] else
                   ", never verified"),
                0.5,
                {"source": row["source"], "kind": row["kind"], "url": row["url"],
                 "auth": row["auth"], "rate_limit": row["rate_limit"],
                 "formats": json.loads(row["formats"] or "[]"),
                 "verified_at": row["verified_at"],
                 "reachable": row["reachable"]}))

        for name, criterion in _validation_criteria(conn, dataset_names):
            results.append(Result("criterion", criterion,
                                  f"recorded in {name}", 0.4, {"source_record": name}))

        return Response(
            intent="data", results=tuple(results), filtered_out=eliminated,
            tier_reached=tier if results else 2,
            next_step=("check each access point's verified_at before depending on it; "
                       "an address recorded a year ago is a hypothesis"
                       if any(r.kind == "access_point" for r in results) else
                       "no access points are recorded for these; the intake extracts "
                       "them during scouting, so this is a gap rather than an absence"),
            partial=bool(degraded), notes=tuple(degraded))
    finally:
        conn.close()


def find_precedent(resource_or_topic: str, limit: int = 10, *,
                   db_path: Path | None = None,
                   cfg: CatalogueConfig | None = None) -> Response:
    """R6 - has this been used before, and what happened?"""
    cfg = cfg or CatalogueConfig.load()
    conn = _conn(db_path)
    try:
        target = _resolve_note(conn, resource_or_topic)
        results: list[Result] = []
        seen: set[str] = set()

        if target:
            for src, relation in _incoming_any(conn, target):
                if _layer(conn, src) != "application" or src in seen:
                    continue
                # The Application Index lists every record, so it links to all
                # of them. A hub is not a precedent.
                if is_hub(_note_type(conn, src)):
                    continue
                seen.add(src)
                results.append(Result(
                    "application", src,
                    f"links to {target} via {relation}", 0.9,
                    _application_fields(conn, src)))

        scores, best, degraded, tier = _search(conn, resource_or_topic, cfg,
                                               layers=("application",), pool=40)
        for name, score in sorted(scores.items(), key=lambda kv: -kv[1]):
            if name in seen or len(results) >= limit:
                continue
            if is_hub(_note_type(conn, name)):
                continue
            seen.add(name)
            results.append(Result("application", name, _why(best.get(name), ""),
                                  score * 0.8, _application_fields(conn, name)))

        return Response(
            intent="precedent", results=tuple(results),
            tier_reached=3 if results else 1,
            next_step=("read 'What The Catalogue Should Learn' in each - that section "
                       "is where a record states a requirement rather than a memory"
                       if results else
                       "no precedent recorded. If you use it, write the record: an "
                       "unrecorded use teaches the catalogue nothing"),
            partial=bool(degraded), notes=tuple(degraded))
    finally:
        conn.close()


def get_note(name: str, *, db_path: Path | None = None) -> dict[str, Any]:
    """Tier 3, directly. Frontmatter and body, from the index."""
    conn = _conn(db_path)
    try:
        resolved = _resolve_note(conn, name)
        if not resolved:
            return {"found": False, "name": name,
                    "why": f"no note named '{name}'; names are the note's filename "
                           f"without .md"}
        row = conn.execute("SELECT * FROM note WHERE name = ?", (resolved,)).fetchone()
        return {"found": True, "name": row["name"], "layer": row["layer"],
                "type": row["type"], "path": row["path"],
                "frontmatter": json.loads(row["frontmatter"]),
                "body": row["body"],
                "links_out": [dict(r) for r in conn.execute(
                    "SELECT dst, relation FROM link WHERE src = ?", (resolved,))],
                "links_in": [dict(r) for r in conn.execute(
                    "SELECT src, relation FROM link WHERE dst = ?", (resolved,))]}
    finally:
        conn.close()


# ------------------------------------------------------- the one permitted write

REQUIRED_RECORD_FIELDS = ("project", "stage", "outcome")
RECORD_SECTIONS = ("What Was Needed", "What Was Found And Taken", "What It Replaced",
                   "What The Catalogue Should Learn")


def record_application(record: dict[str, Any], *, vault: Path | None = None,
                       db_path: Path | None = None,
                       attested_by: str = "agent") -> dict[str, Any]:
    """Append an application record. The single write Mode C may perform.

    Records written by a tool are marked `attested_by: agent` so they can be
    weighted differently from ones a person wrote. The value of this call is
    that writing a record is a tool call at the end of a task rather than a
    chore to remember afterwards - which is the difference between records
    accumulating and records not existing.
    """
    policy.check_consult_write("record_application")
    root = Path(vault) if vault else vault_root()

    missing = [f for f in REQUIRED_RECORD_FIELDS if not record.get(f)]
    if missing:
        raise ValueError(f"application record is missing required field(s): {missing}")
    if attested_by not in {"user", "agent"}:
        raise ValueError("attested_by must be 'user' or 'agent'")

    body_sections = record.get("sections") or {}
    empty = [s for s in RECORD_SECTIONS if not str(body_sections.get(s, "")).strip()]
    if empty:
        raise ValueError(
            f"an application record must answer every section; missing: {empty}. "
            f"'What The Catalogue Should Learn' is the one that turns a diary entry "
            f"into a requirement.")

    project = str(record["project"]).strip()
    title = record.get("title") or f"Application - {project}"
    safe = re.sub(r"[^A-Za-z0-9 &_.-]", "", str(title)).strip() or "Application - Untitled"
    path = root / "09-Applications" / f"{safe}.md"
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        raise FileExistsError(f"{path.name} already exists; edit it rather than "
                              f"writing a second record for the same engagement")

    frontmatter = {
        "type": "application_record",
        "project": project,
        "stage": record["stage"],
        "date_range": record.get("date_range", ""),
        "status": record.get("status", "active"),
        "resources_used": record.get("resources_used", []),
        "patterns_discovered": record.get("patterns_discovered", []),
        "domains": record.get("domains", []),
        "outcome": record["outcome"],
        "attested_by": attested_by,
    }
    lines = ["---"]
    for key, value in frontmatter.items():
        lines.append(f"{key}: {json.dumps(value, ensure_ascii=False)}"
                     if isinstance(value, (list, dict))
                     else f'{key}: "{value}"')
    lines.append("---")
    lines.append("")
    lines.append(f"# {safe}")
    for section in RECORD_SECTIONS:
        lines.append("")
        lines.append(f"## {section}")
        lines.append(str(body_sections[section]).strip())
    lines.append("")
    lines.append("## Semantic Links")
    lines.append("- [application_hub:: [[Application Index]]]")
    for resource in record.get("applied_resources", []):
        lines.append(f"- [applied_resource:: [[{resource}]]]")
    for topic in record.get("related_topics", []):
        lines.append(f"- [related_topic:: [[{topic}]]]")
    lines.append("")

    path.write_text("\n".join(lines), encoding="utf-8")

    # Markdown is truth; the index catches up. Failing to refresh must not
    # fail the write, because the note is already the authoritative record.
    refreshed = True
    try:
        index_mod.refresh(root, db_path, since=time.time() - 5)
    except Exception:                                       # pragma: no cover
        refreshed = False
    return {"path": str(path), "name": safe, "attested_by": attested_by,
            "index_refreshed": refreshed}


# ------------------------------------------------- typed params (spec 4.3/10.3)

SEARCH_PARAMS_SCHEMA: dict[str, Any] = {
    "$id": "catalogue/search_params/v1",
    "type": "object",
    "additionalProperties": False,
    "required": ["intent", "terms"],
    "properties": {
        "intent": {"enum": list(INTENTS)},
        "terms": {"type": "array", "items": {"type": "string"},
                  "minItems": 1, "maxItems": 8},
        "domain": {"type": "string", "description": "must exist in the domain register"},
        "filters": {
            "type": "object",
            "additionalProperties": False,
            "properties": {
                "license_class": {"enum": list(LICENSE_CLASSES)},
                "deployment_target": {"type": "string"},
                "hardware_footprint": {"type": "string"},
                "max_age_days": {"type": "integer", "minimum": 1},
            },
        },
        "source": {"type": "string", "description": "repo_key, for intent=technique"},
        "limit": {"type": "integer", "minimum": 1, "maximum": 50, "default": 10},
    },
}


def validate_params(params: dict[str, Any], *, vault: Path | None = None) -> dict[str, Any]:
    """Validate the one typed object a model is permitted to produce.

    `additionalProperties: false` throughout, enums closed, and `domain`
    checked against the register - so an invalid domain is a validation error
    rather than a silent miss, and the model cannot widen its own permissions
    by inventing a field.
    """
    from .integrity import known_topic_keys

    if not isinstance(params, dict):
        raise ValueError("search params must be an object")
    allowed = set(SEARCH_PARAMS_SCHEMA["properties"])
    unknown = set(params) - allowed
    if unknown:
        raise ValueError(f"unknown search parameter(s): {sorted(unknown)}")
    intent = params.get("intent")
    if intent not in INTENTS:
        raise ValueError(f"intent must be one of {list(INTENTS)}")
    terms = params.get("terms")
    if not isinstance(terms, list) or not 1 <= len(terms) <= 8 \
            or not all(isinstance(t, str) and t.strip() for t in terms):
        raise ValueError("terms must be 1-8 non-empty strings")

    filters = params.get("filters") or {}
    if not isinstance(filters, dict):
        raise ValueError("filters must be an object")
    filter_allowed = set(SEARCH_PARAMS_SCHEMA["properties"]["filters"]["properties"])
    unknown_filters = set(filters) - filter_allowed
    if unknown_filters:
        raise ValueError(f"unknown filter(s): {sorted(unknown_filters)}")
    if filters.get("license_class") and filters["license_class"] not in LICENSE_CLASSES:
        raise ValueError(f"license_class must be one of {list(LICENSE_CLASSES)}")
    if "max_age_days" in filters and (not isinstance(filters["max_age_days"], int)
                                      or filters["max_age_days"] < 1):
        raise ValueError("max_age_days must be a positive integer")

    domain = params.get("domain")
    if domain:
        known = known_topic_keys(Path(vault) if vault else vault_root())
        if domain not in known:
            raise ValueError(
                f"domain '{domain}' is not in the register. The scout may not invent "
                f"a domain; edit [[Scouting Domains]] to add one.")

    limit = params.get("limit", 10)
    if not isinstance(limit, int) or not 1 <= limit <= 50:
        raise ValueError("limit must be an integer between 1 and 50")

    return {"intent": intent, "terms": [t.strip() for t in terms], "domain": domain,
            "filters": dict(filters), "source": params.get("source"), "limit": limit}


def dispatch(params: dict[str, Any], *, db_path: Path | None = None,
             vault: Path | None = None, cfg: CatalogueConfig | None = None) -> Response:
    """Validate, then route to the query the intent names."""
    valid = validate_params(params, vault=vault)
    query = " ".join(valid["terms"])
    limit = valid["limit"]
    filters = dict(valid["filters"])
    if valid["domain"]:
        query = f"{query} {valid['domain']}"
    intent = valid["intent"]
    if intent == "orient":
        return orient(query, limit, db_path=db_path, cfg=cfg)
    if intent == "donor":
        return find_donor(query, filters, limit, db_path=db_path, cfg=cfg)
    if intent == "pattern":
        return find_pattern(query, limit, db_path=db_path, cfg=cfg)
    if intent == "technique":
        return find_technique(query, valid["source"], limit, db_path=db_path, cfg=cfg)
    if intent == "data":
        return find_data(query, None, limit, db_path=db_path, cfg=cfg)
    return find_precedent(query, limit, db_path=db_path, cfg=cfg)


# ------------------------------------------------------------------- internals

def _top(scores: dict[str, float], best: dict[str, Hit], layers: Sequence[str],
         conn: sqlite3.Connection, limit: int) -> list[tuple[str, float, Hit | None]]:
    wanted = set(layers)
    out: list[tuple[str, float, Hit | None]] = []
    for name, score in sorted(scores.items(), key=lambda kv: -kv[1]):
        if _layer(conn, name) not in wanted:
            continue
        # A hub routes to answers; returning one as an answer is the retrieval
        # equivalent of handing somebody the index of a book they asked about.
        if is_hub(_note_type(conn, name)):
            continue
        out.append((name, score, best.get(name)))
        if len(out) >= limit:
            break
    return out


def _layer(conn: sqlite3.Connection, name: str) -> str:
    row = conn.execute("SELECT layer FROM note WHERE name = ?", (name,)).fetchone()
    return (row["layer"] or "") if row else ""


def _note_type(conn: sqlite3.Connection, name: str) -> str:
    row = conn.execute("SELECT type FROM note WHERE name = ?", (name,)).fetchone()
    return (row["type"] or "") if row else ""


def _resolve_note(conn: sqlite3.Connection, name: str) -> str | None:
    row = conn.execute("SELECT name FROM note WHERE name = ?", (name,)).fetchone()
    if row:
        return row["name"]
    row = conn.execute("SELECT name FROM note WHERE LOWER(name) = LOWER(?)",
                       (name,)).fetchone()
    if row:
        return row["name"]
    row = conn.execute(
        "SELECT name FROM resource_facet WHERE repo_key = ? OR canonical_url = ?",
        (name, name)).fetchone()
    return row["name"] if row else None


def _note_for_source(conn: sqlite3.Connection, source: str) -> str | None:
    row = conn.execute("SELECT name FROM resource_facet WHERE repo_key = ?",
                       (source,)).fetchone()
    if row:
        return row["name"]
    return _resolve_note(conn, source)


def _incoming(conn: sqlite3.Connection, dst: str, relation: str) -> list[str]:
    return [r["src"] for r in conn.execute(
        "SELECT src FROM link WHERE dst = ? AND relation = ?", (dst, relation))]


def _incoming_any(conn: sqlite3.Connection, dst: str) -> list[tuple[str, str]]:
    return [(r["src"], r["relation"]) for r in conn.execute(
        "SELECT src, relation FROM link WHERE dst = ?", (dst,))]


def _children_of(conn: sqlite3.Connection, topic: str) -> list[str]:
    return _incoming(conn, topic, "parent_topic")


def _parent_topic(conn: sqlite3.Connection, name: str) -> str:
    row = conn.execute(
        "SELECT dst FROM link WHERE src = ? AND relation = 'parent_topic'",
        (name,)).fetchone()
    return row["dst"] if row else ""


def _related_patterns(conn: sqlite3.Connection, pattern: str, limit: int = 4) -> list[str]:
    rows = conn.execute(
        "SELECT DISTINCT l2.src AS name FROM link l1 JOIN link l2 ON l1.dst = l2.dst "
        "JOIN note n ON n.name = l2.src "
        "WHERE l1.src = ? AND l2.src != ? AND n.layer = 'pattern' LIMIT ?",
        (pattern, pattern, limit)).fetchall()
    return [r["name"] for r in rows]


def _sources_with_access_points(conn: sqlite3.Connection) -> set[str]:
    return {row["source"] for row in conn.execute(
        "SELECT DISTINCT source FROM access_point")}


def _access_points_for(conn: sqlite3.Connection, sources: Sequence[str]) -> list[sqlite3.Row]:
    if not sources:
        return []
    keys = list(sources)
    for name in sources:
        row = conn.execute("SELECT repo_key FROM resource_facet WHERE name = ?",
                           (name,)).fetchone()
        if row and row["repo_key"]:
            keys.append(row["repo_key"])
    marks = ",".join("?" for _ in keys)
    return conn.execute(
        f"SELECT * FROM access_point WHERE source IN ({marks}) ORDER BY source, kind",
        keys).fetchall()


def _validation_criteria(conn: sqlite3.Connection, datasets: Sequence[str]
                         ) -> list[tuple[str, str]]:
    """Criteria come from application records, never from a model.

    `patterns_discovered` on a record is where a real engagement wrote down
    what "correct" looked like; anything else would be invention.
    """
    out: list[tuple[str, str]] = []
    rows = conn.execute(
        "SELECT name, frontmatter FROM note WHERE layer = 'application'").fetchall()
    for row in rows:
        try:
            data = json.loads(row["frontmatter"])
        except Exception:                                   # pragma: no cover
            continue
        for item in data.get("patterns_discovered") or []:
            text = str(item)
            if "valid" in text.lower() or "verif" in text.lower():
                out.append((row["name"], text))
    return out[:5]


def _resource_fields(facet: dict | None) -> dict[str, Any]:
    facet = facet or {}
    out = {key: facet.get(key) for key in
           ("repo_key", "canonical_url", "license_class", "maturity_stage",
            "deployment_target", "hardware_footprint", "ecosystem",
            "domain_primary", "primary_topic", "agent_surface", "is_container",
            "pushed_at", "stars", "application_count",
            "bottom_line") if facet.get(key) is not None}
    # The class name is not the answer anyone wants. `Copyleft` does not say
    # what it stops you doing, and what it stops you doing depends on the
    # posture rather than on the licence - so answer the question directly.
    # Derived on read, never stored: it is a function of a recorded fact and a
    # configured posture, and storing it would let the two drift.
    out["permitted_uses"] = list(permitted_uses(facet.get("license_class")))
    return out


def _topic_fields(conn: sqlite3.Connection, name: str) -> dict[str, Any]:
    row = conn.execute("SELECT frontmatter FROM note WHERE name = ?", (name,)).fetchone()
    data = json.loads(row["frontmatter"]) if row else {}
    return {"topic_key": data.get("topic_key"),
            "resource_count": data.get("resource_count"),
            "inclusion_criteria": data.get("inclusion_criteria"),
            "canonical_vocabulary": data.get("canonical_vocabulary")}


def _pattern_fields(conn: sqlite3.Connection, name: str) -> dict[str, Any]:
    row = conn.execute("SELECT frontmatter FROM note WHERE name = ?", (name,)).fetchone()
    data = json.loads(row["frontmatter"]) if row else {}
    return {"pattern_key": data.get("pattern_key"), "examples": data.get("examples"),
            "topic_keys": data.get("topic_keys")}


def _application_fields(conn: sqlite3.Connection, name: str) -> dict[str, Any]:
    row = conn.execute("SELECT frontmatter, body FROM note WHERE name = ?",
                       (name,)).fetchone()
    if not row:
        return {}
    data = json.loads(row["frontmatter"])
    from .notes import split_sections
    sections = split_sections(row["body"])
    return {"project": data.get("project"), "stage": data.get("stage"),
            "outcome": data.get("outcome"), "domains": data.get("domains"),
            "attested_by": data.get("attested_by", "user"),
            "patterns_discovered": data.get("patterns_discovered"),
            "what_the_catalogue_should_learn":
                sections.get("What The Catalogue Should Learn", "")[:600]}
