"""Derived views, regenerated from the notes rather than maintained by hand.

The vault's operating rules say the taxonomy matrix and the route-map counts
are "regenerated by the build, never edited by hand". Until now the only thing
that could regenerate them was `build_solutions_library.py`, which also
rewrites resource notes from its own database and has overwritten hand-written
prose before ([[Implementation Brief]] 2.1). So the safe option was to edit the
views by hand, which the rules forbid, and the 2026-09 cohort did exactly that
for seventeen rows.

This module is the missing third option: regenerate the views, touch nothing
else. It reads note frontmatter, renders three blocks, and writes them back in
place. It has no model, no network, and no database - the notes are the only
input, which is what makes `MARKDOWN_IS_TRUTH` operational here rather than
aspirational.

Three views, and the reason each is derived rather than written:

  Taxonomy matrix     a table of nine frontmatter fields per resource. Every
                      value already exists in a note; a second copy typed by
                      hand is a second copy that can be wrong, and it was -
                      29 rows disagreed with their notes on `license_class`,
                      the field `find_donor` eliminates on.
  Topic membership    `## Approved Resources` and `resource_count`. The list
                      is exactly the resources whose `primary_topic` is that
                      topic, so maintaining it separately is transcription.
  Route-map counts    the `(n approved)` figures in the Master Index, and
                      `topic_count`. Same argument, one level up.

`resource_count` matters beyond tidiness: `scout.rank.gap_fit` reads it and
carries the largest ranking weight, so a stale count silently mis-ranks every
candidate for that topic.
"""
from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Sequence

from .config import INDEX_FOLDER, vault_root
from . import notes as notes_mod

# The nine taxonomy axes, in the order the matrix presents them. This tuple is
# the column order and nothing else may decide it.
AXES: tuple[str, ...] = (
    "ecosystem", "domain_primary", "maturity_stage", "license_class",
    "deployment_target", "interface_protocol", "data_locality",
    "hardware_footprint", "security_compliance", "agent_surface",
)

MATRIX_HEADER = (
    "| Resource | Ecosystem | Domain | Maturity | License | Target | Protocol "
    "| Locality | Footprint | Security | Agent |\n"
    "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |"
)

TAXONOMY_NOTE = "Taxonomy Index"
MASTER_NOTE = "Master Index"

# Resources held for review are shown in the matrix - they exist and a person
# may need to compare them - but they are not counted as approved anywhere.
MATRIX_LAYERS = ("resource", "review")


@dataclass(frozen=True)
class Change:
    """One view that did not match what the notes say."""
    note: str
    view: str
    detail: str

    def __str__(self) -> str:                        # pragma: no cover - display
        return f"{self.note:<28} {self.view:<18} {self.detail}"


# ------------------------------------------------------------- rendering

def _facet(note: notes_mod.Note, axis: str) -> str:
    return note.string(axis) or "Unknown"


def matrix_rows(notes: Sequence[notes_mod.Note]) -> list[str]:
    """One row per resource, sorted by name so a rebuild is reproducible."""
    rows = []
    for note in sorted((n for n in notes if n.layer in MATRIX_LAYERS
                        and n.string("canonical_url")),
                       key=lambda n: n.name.lower()):
        cells = " | ".join(_facet(note, axis) for axis in AXES)
        rows.append(f"| [[{note.name}]] | {cells} |")
    return rows


def render_matrix(notes: Sequence[notes_mod.Note]) -> str:
    return MATRIX_HEADER + "\n" + "\n".join(matrix_rows(notes))


def members_of(notes: Sequence[notes_mod.Note], topic_name: str) -> list[str]:
    """Resources whose `primary_topic` is this topic, approved only."""
    return sorted((n.name for n in notes
                   if n.layer == "resource"
                   and (n.string("primary_topic") or "") == topic_name),
                  key=str.lower)


def held_for(notes: Sequence[notes_mod.Note], topic_name: str) -> list[str]:
    return sorted((n.name for n in notes
                   if n.layer == "review"
                   and (n.string("primary_topic") or "") == topic_name),
                  key=str.lower)


LIST_LINK = re.compile(r"^- \[\[([^\]]+)\]\]\s*$", re.M)


def reconcile_list(existing: str, wanted: Sequence[str]) -> str:
    """Correct a link list's membership without reordering what is already there.

    The view owns *which* resources a topic contains, because that is a fact
    about their frontmatter. It does not own the *order*, because that is a
    presentation choice a person may have made deliberately - the existing
    lists run in the order the resources were catalogued, and alphabetising
    fourteen of them would be a derived view rewriting authored content to
    suit itself.

    So: drop entries that no longer qualify, keep the rest in place, and append
    newcomers in a deterministic order.
    """
    wanted_set = list(dict.fromkeys(wanted))
    present = LIST_LINK.findall(existing or "")
    kept = [name for name in present if name in wanted_set]
    added = [name for name in wanted_set if name not in kept]
    final = kept + added
    return "\n".join(f"- [[{name}]]" for name in final) or "- None yet."


# --------------------------------------------------------------- rewriting

def _section_span(body: str, heading: str) -> tuple[int, int] | None:
    """Character range of a `## Heading` section's content, excluding the
    heading line itself and the blank line before the next heading."""
    match = re.search(rf"^##\s+{re.escape(heading)}\s*$", body, re.M)
    if not match:
        return None
    start = match.end()
    nxt = re.search(r"^##\s+", body[start:], re.M)
    return start, (start + nxt.start() if nxt else len(body))


def replace_section(text: str, heading: str, content: str) -> str:
    """Swap one section's body, leaving every other byte of the note alone."""
    span = _section_span(text, heading)
    if span is None:
        return text
    start, end = span
    return text[:start] + "\n" + content.strip("\n") + "\n\n" + text[end:]


def set_frontmatter_scalar(text: str, key: str, value: object) -> str:
    """Rewrite one frontmatter value in place. Absent keys are not invented -
    adding a field would be schema drift, which is not this module's business.
    """
    pattern = re.compile(rf"^({re.escape(key)}:\s*)(.*)$", re.M)
    match = pattern.search(text.split("---", 2)[1] if text.startswith("---") else "")
    if not match:
        return text
    head, _, rest = text.partition("---")
    block, sep, body = rest.partition("\n---")
    return head + "---" + pattern.sub(rf"\g<1>{value}", block, count=1) + sep + body


# ------------------------------------------------------------------ views

def _path_for(vault: Path, name: str) -> Path:
    return vault / INDEX_FOLDER / f"{name}.md"


MATRIX_ROW = re.compile(r"^\|\s*\[\[[^\]]+\]\]\s*\|.*\|\s*$", re.M)


def strip_stray_rows(text: str) -> str:
    """Remove matrix rows that are not inside the Resource Matrix section.

    A row outside the matrix is not a smaller problem than a wrong row - it is
    invisible to anything reading the section, and it duplicates a resource
    that also appears in the real table. The 2026-09 hand-edit produced
    seventeen of them by appending to the end of the file.
    """
    span = _section_span(text, "Resource Matrix")
    if span is None:
        return text
    start, end = span
    before, inside, after = text[:start], text[start:end], text[end:]
    return before + inside + MATRIX_ROW.sub("", after)


def taxonomy_view(vault: Path,
                  notes: Sequence[notes_mod.Note]) -> tuple[Path, str, str] | None:
    """None when the note is absent. A vault without a taxonomy hub is a
    smaller vault, not a broken one, and a view that raises on it would make
    the integrity check unrunnable on any partial vault."""
    path = _path_for(vault, TAXONOMY_NOTE)
    if not path.exists():
        return None
    current = path.read_text(encoding="utf-8")
    wanted = strip_stray_rows(current)
    wanted = replace_section(wanted, "Resource Matrix", render_matrix(notes))
    counted = len([n for n in notes if n.layer in MATRIX_LAYERS
                   and n.string("canonical_url")])
    wanted = set_frontmatter_scalar(wanted, "resource_count", counted)
    return path, current, wanted


def topic_views(vault: Path, notes: Sequence[notes_mod.Note]
                ) -> Iterable[tuple[Path, str, str]]:
    for note in sorted((n for n in notes if n.type == "topic_index"),
                       key=lambda n: n.name):
        topic_name = note.name.replace("Topic - ", "")
        members = members_of(notes, topic_name)
        held = held_for(notes, topic_name)
        current = note.path.read_text(encoding="utf-8")
        approved_span = _section_span(current, "Approved Resources")
        review_span = _section_span(current, "Review Queue")
        wanted = replace_section(
            current, "Approved Resources",
            reconcile_list(current[slice(*approved_span)] if approved_span else "",
                           members))
        wanted = replace_section(
            wanted, "Review Queue",
            reconcile_list(current[slice(*review_span)] if review_span else "",
                           held))
        wanted = set_frontmatter_scalar(wanted, "resource_count", len(members))
        wanted = set_frontmatter_scalar(wanted, "review_count", len(held))
        yield note.path, current, wanted


ROUTE_LINE = re.compile(r"^- \[\[(?P<topic>Topic - [^\]]+)\]\](?P<tail>.*)$", re.M)


def master_view(vault: Path,
                notes: Sequence[notes_mod.Note]) -> tuple[Path, str, str] | None:
    """The route map's `(n approved)` figures, and `topic_count`.

    Only the count is rewritten. Which topics appear, and in what order, is a
    routing decision a person made; a derived view may correct a number but it
    may not decide what the map contains.
    """
    path = _path_for(vault, MASTER_NOTE)
    if not path.exists():
        return None
    current = path.read_text(encoding="utf-8")
    counts = {f"Topic - {t}": len(members_of(notes, t))
              for t in {(n.string("primary_topic") or "") for n in notes}}
    topics = [n for n in notes if n.type == "topic_index"]
    for note in topics:
        counts.setdefault(note.name, len(members_of(
            notes, note.name.replace("Topic - ", ""))))

    def fix(match: re.Match) -> str:
        topic = match.group("topic")
        if topic not in counts:
            return match.group(0)
        return f"- [[{topic}]] ({counts[topic]} approved)"

    wanted = ROUTE_LINE.sub(fix, current)
    wanted = set_frontmatter_scalar(wanted, "topic_count", len(topics))
    return path, current, wanted


# ------------------------------------------------------------------- entry

def run(vault: Path | None = None, *, write: bool = False) -> list[Change]:
    """Compare every derived view against the notes. Returns what differs.

    With `write=False` nothing is touched, which is what makes this usable as
    an integrity gate. With `write=True` the views are brought into line and
    the same list is returned, describing what was corrected.
    """
    vault = Path(vault or vault_root())
    loaded = notes_mod.load_vault(vault)
    changes: list[Change] = []

    jobs: list[tuple[str, tuple[Path, str, str]]] = [
        (name, job) for name, job in
        (("taxonomy matrix", taxonomy_view(vault, loaded)),
         ("route map", master_view(vault, loaded)))
        if job is not None
    ]
    jobs.extend(("topic membership", job) for job in topic_views(vault, loaded))

    for view, (path, current, wanted) in jobs:
        if current == wanted:
            continue
        changes.append(Change(path.stem, view, _describe(current, wanted)))
        if write:
            path.write_text(wanted, encoding="utf-8")
    return changes


def _describe(current: str, wanted: str) -> str:
    """A one-line reason, so a drift report says what actually moved."""
    before, after = current.splitlines(), wanted.splitlines()
    added = [line for line in after if line not in before]
    removed = [line for line in before if line not in after]
    if not added and not removed:
        return "same lines, different order or spacing"
    parts = []
    if added:
        parts.append(f"+{len(added)}: {added[0].strip()[:60]}")
    if removed:
        parts.append(f"-{len(removed)}: {removed[0].strip()[:60]}")
    return "; ".join(parts)
